[package]
name = "rust"
version = "0.1.0"
authors = ["Liquid <a.marcius26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
rand = "0.7.3"
rustbitmap = "0.1.0"
line_drawing = "0.8.0"
